# Preprocessing

In [3]:
import pandas as pd

In [4]:
df=pd.read_csv('test_combined.csv')

In [5]:
df.head()

,type,status,departure_iata,departure_icao,departure_terminal,departure_scheduled,departure_estimated,departure_actual,departure_runway_estimated,departure_runway_actual,...,arrival_icao,arrival_terminal,arrival_scheduled,arrival_estimated,airline_name,airline_iata,airline_icao,flight_number,flight_iata,flight_icao
0,departure,active,lhe,opla,NaN,2023-07-17t20:35:00.000,NaN,NaN,2023-07-17t20:46:00.000,2023-07-17t20:46:00.000,...,opkc,NaN,2023-07-17t22:20:00.000,2023-07-17t22:12:00.000,flyjinnah,9p,fjl,847,9p847,fjl847
1,departure,active,lhe,opla,m,2023-07-27t08:00:00.000,NaN,NaN,NaN,NaN,...,oerk,t2,2023-07-27t10:00:00.000,NaN,pakistan international airlines,pk,pia,725,pk725,pia725
2,departure,active,lhe,opla,m,2023-07-27t08:00:00.000,NaN,NaN,NaN,NaN,...,omdb,1,2023-07-27t10:00:00.000,NaN,ethiopian airlines,et,eth,4359,et4359,eth4359
3,departure,unknown,lhe,opla,m,2023-07-28t16:45:00.000,NaN,NaN,NaN,NaN,...,oejn,NaN,2023-07-28t20:30:00.000,NaN,airblue,pa,abq,470,pa470,abq470
4,departure,active,lhe,opla,m,2023-07-19t04:15:00.000,NaN,NaN,2023-07-19t04:18:00.000,2023-07-19t04:18:00.000,...,omaa,3,2023-07-19t06:35:00.000,2023-07-19t06:08:00.000,klm,kl,klm,3932,kl3932,klm3932

In [6]:
df['arrival_estimated'].fillna(pd.NaT)
df['arrival_scheduled'].fillna(pd.NaT)

0        2023-07-17t22:20:00.000
1        2023-07-27t10:00:00.000
2        2023-07-27t10:00:00.000
3        2023-07-28t20:30:00.000
4        2023-07-19t06:35:00.000
                  ...
14905    2023-11-24t02:05:00.000
14906    2023-11-25t22:05:00.000
14907    2023-11-25t05:05:00.000
14908    2023-11-27t10:45:00.000
14909    2023-11-26t04:15:00.000
Name: arrival_scheduled, Length: 14910, dtype: object

In [7]:
df.head()

,type,status,departure_iata,departure_icao,departure_terminal,departure_scheduled,departure_estimated,departure_actual,departure_runway_estimated,departure_runway_actual,...,arrival_icao,arrival_terminal,arrival_scheduled,arrival_estimated,airline_name,airline_iata,airline_icao,flight_number,flight_iata,flight_icao
0,departure,active,lhe,opla,NaN,2023-07-17t20:35:00.000,NaN,NaN,2023-07-17t20:46:00.000,2023-07-17t20:46:00.000,...,opkc,NaN,2023-07-17t22:20:00.000,2023-07-17t22:12:00.000,flyjinnah,9p,fjl,847,9p847,fjl847
1,departure,active,lhe,opla,m,2023-07-27t08:00:00.000,NaN,NaN,NaN,NaN,...,oerk,t2,2023-07-27t10:00:00.000,NaN,pakistan international airlines,pk,pia,725,pk725,pia725
2,departure,active,lhe,opla,m,2023-07-27t08:00:00.000,NaN,NaN,NaN,NaN,...,omdb,1,2023-07-27t10:00:00.000,NaN,ethiopian airlines,et,eth,4359,et4359,eth4359
3,departure,unknown,lhe,opla,m,2023-07-28t16:45:00.000,NaN,NaN,NaN,NaN,...,oejn,NaN,2023-07-28t20:30:00.000,NaN,airblue,pa,abq,470,pa470,abq470
4,departure,active,lhe,opla,m,2023-07-19t04:15:00.000,NaN,NaN,2023-07-19t04:18:00.000,2023-07-19t04:18:00.000,...,omaa,3,2023-07-19t06:35:00.000,2023-07-19t06:08:00.000,klm,kl,klm,3932,kl3932,klm3932

In [8]:
df.drop(['type','departure_terminal','arrival_terminal', 'flight_number', 'flight_iata', 'flight_icao'], axis=1)

,status,departure_iata,departure_icao,departure_scheduled,departure_estimated,departure_actual,departure_runway_estimated,departure_runway_actual,arrival_iata,arrival_icao,arrival_scheduled,arrival_estimated,airline_name,airline_iata,airline_icao
0,active,lhe,opla,2023-07-17t20:35:00.000,NaN,NaN,2023-07-17t20:46:00.000,2023-07-17t20:46:00.000,khi,opkc,2023-07-17t22:20:00.000,2023-07-17t22:12:00.000,flyjinnah,9p,fjl
1,active,lhe,opla,2023-07-27t08:00:00.000,NaN,NaN,NaN,NaN,ruh,oerk,2023-07-27t10:00:00.000,NaN,pakistan international airlines,pk,pia
2,active,lhe,opla,2023-07-27t08:00:00.000,NaN,NaN,NaN,NaN,dxb,omdb,2023-07-27t10:00:00.000,NaN,ethiopian airlines,et,eth
3,unknown,lhe,opla,2023-07-28t16:45:00.000,NaN,NaN,NaN,NaN,jed,oejn,2023-07-28t20:30:00.000,NaN,airblue,pa,abq
4,active,lhe,opla,2023-07-19t04:15:00.000,NaN,NaN,2023-07-19t04:18:00.000,2023-07-19t04:18:00.000,auh,omaa,2023-07-19t06:35:00.000,2023-07-19t06:08:00.000,klm,kl,klm
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14905,active,lhe,opla,2023-11-23t23:15:00.000,NaN,NaN,2023-11-23t23:27:00.000,2023-11-23t23:27:00.000,shj,omsj,2023-11-24t02:05:00.000,2023-11-24t01:34:00.000,airblue,pa,abq
14906,active,lhe,opla,2023-11-25t18:45:00.000,NaN,NaN,2023-11-25t19:05:00.000,2023-11-25t19:05:00.000,jed,oejn,2023-11-25t22:05:00.000,2023-11-25t22:09:00.000,pakistan international airlines,pk,pia
14907,active,lhe,opla,2023-11-25t02:55:00.000,NaN,NaN,2023-11-25t03:07:00.000,2023-11-25t03:07:00.000,doh,othh,2023-11-25t05:05:00.000,2023-11-25t04:33:00.000,british airways,ba,baw
14908,active,lhe,opla,2023-11-27t08:35:00.000,NaN,NaN,NaN,NaN,doh,othh,2023-11-27t10:45:00.000,NaN,oman air,wy,oma
14909,active,lhe,opla,2023-11-26t01:45:00.000,NaN,NaN,NaN,NaN,ika,oiie,2023-11-26t04:15:00.000,NaN,mahan air,w5,irm

In [9]:
def datetime(df):
  return pd.to_datetime(df)

In [10]:
df['departure_scheduled']=df['departure_scheduled'].apply(datetime)
df['arrival_scheduled']=df['arrival_scheduled'].apply(datetime)
df['arrival_estimated']=df['arrival_estimated'].apply(datetime)

In [11]:
df['year'] = df['departure_scheduled'].dt.year
df['month'] = df['departure_scheduled'].dt.month
df['day'] = df['departure_scheduled'].dt.day

In [12]:
df.head()

,type,status,departure_iata,departure_icao,departure_terminal,departure_scheduled,departure_estimated,departure_actual,departure_runway_estimated,departure_runway_actual,...,arrival_estimated,airline_name,airline_iata,airline_icao,flight_number,flight_iata,flight_icao,year,month,day
0,departure,active,lhe,opla,NaN,2023-07-17 20:35:00,NaN,NaN,2023-07-17t20:46:00.000,2023-07-17t20:46:00.000,...,2023-07-17 22:12:00,flyjinnah,9p,fjl,847,9p847,fjl847,2023,7,17
1,departure,active,lhe,opla,m,2023-07-27 08:00:00,NaN,NaN,NaN,NaN,...,NaT,pakistan international airlines,pk,pia,725,pk725,pia725,2023,7,27
2,departure,active,lhe,opla,m,2023-07-27 08:00:00,NaN,NaN,NaN,NaN,...,NaT,ethiopian airlines,et,eth,4359,et4359,eth4359,2023,7,27
3,departure,unknown,lhe,opla,m,2023-07-28 16:45:00,NaN,NaN,NaN,NaN,...,NaT,airblue,pa,abq,470,pa470,abq470,2023,7,28
4,departure,active,lhe,opla,m,2023-07-19 04:15:00,NaN,NaN,2023-07-19t04:18:00.000,2023-07-19t04:18:00.000,...,2023-07-19 06:08:00,klm,kl,klm,3932,kl3932,klm3932,2023,7,19

In [13]:

df['departure_delay'] = (df[['arrival_scheduled', 'arrival_estimated']].max(axis=1) - df[['arrival_scheduled', 'arrival_estimated']].min(axis=1)).dt.total_seconds()


df['departure_delay'] = df['departure_delay'].apply(lambda x: f"{int(x // 3600)} hours {int((x % 3600) // 60)} minutes {int(x % 60)} seconds")

In [14]:
df.head()

,type,status,departure_iata,departure_icao,departure_terminal,departure_scheduled,departure_estimated,departure_actual,departure_runway_estimated,departure_runway_actual,...,airline_name,airline_iata,airline_icao,flight_number,flight_iata,flight_icao,year,month,day,departure_delay
0,departure,active,lhe,opla,NaN,2023-07-17 20:35:00,NaN,NaN,2023-07-17t20:46:00.000,2023-07-17t20:46:00.000,...,flyjinnah,9p,fjl,847,9p847,fjl847,2023,7,17,0 hours 8 minutes 0 seconds
1,departure,active,lhe,opla,m,2023-07-27 08:00:00,NaN,NaN,NaN,NaN,...,pakistan international airlines,pk,pia,725,pk725,pia725,2023,7,27,0 hours 0 minutes 0 seconds
2,departure,active,lhe,opla,m,2023-07-27 08:00:00,NaN,NaN,NaN,NaN,...,ethiopian airlines,et,eth,4359,et4359,eth4359,2023,7,27,0 hours 0 minutes 0 seconds
3,departure,unknown,lhe,opla,m,2023-07-28 16:45:00,NaN,NaN,NaN,NaN,...,airblue,pa,abq,470,pa470,abq470,2023,7,28,0 hours 0 minutes 0 seconds
4,departure,active,lhe,opla,m,2023-07-19 04:15:00,NaN,NaN,2023-07-19t04:18:00.000,2023-07-19t04:18:00.000,...,klm,kl,klm,3932,kl3932,klm3932,2023,7,19,0 hours 27 minutes 0 seconds

In [15]:
import re
def time_to_hours(time_str):
    match = re.match(r'(\d+)\s*hours\s*(\d+)\s*minutes\s*(\d+)\s*seconds', time_str)
    if match:
        hours, minutes, seconds = map(int, match.groups())
        return hours + (minutes / 60) + (seconds / 3600)  # Convert everything to hours
    return 0  
    
df['total_hours'] = df['departure_delay'].apply(time_to_hours)

In [16]:
df['total_hours'].sample(20)

14234    0.000000
7309     0.283333
5648     0.316667
5444     0.583333
11014    0.383333
13523    0.000000
2348     0.333333
6175     0.216667
12938    0.000000
12841    0.200000
3282     0.750000
4604     0.233333
11263    0.116667
3706     0.250000
6686     0.000000
11942    0.083333
1979     0.233333
11512    0.550000
11823    0.000000
13999    0.000000
Name: total_hours, dtype: float64

# Loading Models & Make Predictions

In [45]:
import joblib

# Load your saved models
binary_model = joblib.load('binary.pkl')
multiclass_model = joblib.load('multiclass.pkl')
regression_model = joblib.load('regression.pkl')

In [48]:
X = df[['year', 'month', 'day']]

In [52]:
regression_predictions = regression_model.predict(X)

In [53]:
regression_predictions

array([0.26105179, 0.32362291, 0.32362291, ..., 0.27384525, 0.28434272,
       0.17468385])

In [54]:
regression_df = pd.DataFrame(regression_predictions, columns=['Predictions'])

In [55]:
regression_df.head()

   Predictions
0     0.261052
1     0.323623
2     0.323623
3     0.275846
4     0.320930

In [58]:
regression_df.to_csv('regression_predictions.csv')

In [59]:
df.head()

,type,status,departure_iata,departure_icao,departure_terminal,departure_scheduled,departure_estimated,departure_actual,departure_runway_estimated,departure_runway_actual,...,arrival_estimated,airline_name,airline_iata,airline_icao,flight_number,flight_iata,flight_icao,year,month,day
0,departure,active,lhe,opla,0,2023-07-17 20:35:00,0.0,0.0,2023-07-17t20:46:00.000,2023-07-17t20:46:00.000,...,2023-07-17t22:12:00.000,flyjinnah,9p,fjl,847,9p847,fjl847,2023,7,17
1,departure,active,lhe,opla,m,2023-07-27 08:00:00,0.0,0.0,0,0,...,0,pakistan international airlines,pk,pia,725,pk725,pia725,2023,7,27
2,departure,active,lhe,opla,m,2023-07-27 08:00:00,0.0,0.0,0,0,...,0,ethiopian airlines,et,eth,4359,et4359,eth4359,2023,7,27
3,departure,unknown,lhe,opla,m,2023-07-28 16:45:00,0.0,0.0,0,0,...,0,airblue,pa,abq,470,pa470,abq470,2023,7,28
4,departure,active,lhe,opla,m,2023-07-19 04:15:00,0.0,0.0,2023-07-19t04:18:00.000,2023-07-19t04:18:00.000,...,2023-07-19t06:08:00.000,klm,kl,klm,3932,kl3932,klm3932,2023,7,19

In [113]:
X2 = df[['year', 'month', 'day',
        'total_hours',]]

In [114]:
binary_predictions = binary_model.predict(X2)

C:\Users\Arslan Javed\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:458: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  warnings.warn(

In [115]:
binary_df = pd.DataFrame(binary_predictions, columns=['Predictions'])

In [116]:
binary_df['Predictions'].value_counts()

Predictions
1    14910
Name: count, dtype: int64

In [107]:
X1 = df[['year', 'month', 'day',
        'total_hours',]]

In [108]:
multiclass_predictions = multiclass_model.predict(X1)

In [109]:
multiclass_df = pd.DataFrame(multiclass_predictions, columns=['Predictions'])

In [112]:
multiclass_df.to_csv('multiclass_predictions.csv')

In [17]:
import joblib

# Load your saved models
binary_model = joblib.load('binary.pkl')

In [18]:
X2 = df[['year', 'month', 'day',
        'total_hours',]]

In [19]:
binary_predictions = binary_model.predict(X2)

C:\Users\Arslan Javed\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:458: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  warnings.warn(

In [20]:
binary_df = pd.DataFrame(binary_predictions, columns=['Predictions'])

In [21]:
binary_df.to_csv('binary_predictions.csv')