# Make settings for Kaggle Submission

In [1]:
import pandas as pd

In [26]:
import pandas as pd

# Read the CSV file
df = pd.read_csv('binary_predictions.csv')

# Add a column of IDs (auto-incrementing integers)
df['ID'] = range(1, len(df) + 1)

# Reorder columns to place 'ID' before the first column
cols = ['ID'] + [col for col in df.columns if col != 'ID']
df = df[cols]

In [27]:
df.drop('Unnamed: 0', axis=1, inplace=True)

In [28]:
df

          ID  Predictions
0          1            1
1          2            1
2          3            1
3          4            1
4          5            1
...      ...          ...
14905  14906            1
14906  14907            1
14907  14908            1
14908  14909            1
14909  14910            1

[14910 rows x 2 columns]

In [29]:
df.rename(columns={'Predictions':'Delay'}, inplace=True)

In [30]:
df

          ID  Delay
0          1      1
1          2      1
2          3      1
3          4      1
4          5      1
...      ...    ...
14905  14906      1
14906  14907      1
14907  14908      1
14908  14909      1
14909  14910      1

[14910 rows x 2 columns]

In [22]:
df.to_csv('regression_0613.csv', index=False)

In [31]:
df_new=df.iloc[0:12914]

In [32]:
df_new.tail

<bound method NDFrame.tail of           ID  Delay
0          1      1
1          2      1
2          3      1
3          4      1
4          5      1
...      ...    ...
12909  12910      1
12910  12911      1
12911  12912      1
12912  12913      1
12913  12914      1

[12914 rows x 2 columns]>

In [33]:
df_new.to_csv('binary_0613.csv', index=False)